# Site settings
title: Ahmed Harhash
description: Personal Profile

# User settings
username: Ahmed Harhash
user_title: Software Engineer
email: email@lacentix.me
linkedin_username: lacentix
github_username:  lacentix

exclude: ['package.json', 'src', 'node_modules', 'vendor']
