baseurl: ""    # Make sure this is empty
url: "gabr.kremzein.com"  # Your custom domain URL

# Site settings
title: Abdelrahman Gabr's Resume
description: Personal Profile of Abdelrahman Gabr

# User settings
username: Abdelrahman Gabr
user_title: Computer Engineering Student
email: Abdelrahman_Gabr@tutanota.com

linkedin_username: agabr1
github_username: Gabrcodes

exclude: ['package.json', 'src', 'node_modules', 'vendor']
